# Generated by Django 3.2.9 on 2021-11-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodels',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
